version: '3.7'

networks:
  task-queue-network:
      driver: bridge

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - task-queue-network

  worker1:
    build: .
    volumes:
      - /media/linux_data/data/:/usr/src/app/data
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - task-queue-network

  worker2:
    build: .
    volumes:
      - /media/linux_data/data/:/usr/src/app/data
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - task-queue-network

  worker3:
    build: .
    volumes:
      - /media/linux_data/data/:/usr/src/app/data
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    networks:
        - task-queue-network
